# Generated by Django 4.1 on 2022-08-10 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('piece', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('sale', models.BooleanField()),
                ('calroties', models.FloatField()),
                ('brand', models.CharField(max_length=200)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='meals.category')),
            ],
        ),
    ]
