# Generated by Django 4.0.5 on 2022-08-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('brandUrl', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('nutrition', models.CharField(max_length=200)),
                ('cooking', models.CharField(max_length=200)),
                ('ingredient', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('sale', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TopProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('nutrition', models.CharField(max_length=100)),
                ('ingredient', models.CharField(max_length=100)),
                ('cooking', models.CharField(max_length=100)),
                ('brandUrl', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('sale', models.BooleanField(default=False)),
            ],
        ),
    ]
