# Generated by Django 4.0.5 on 2022-08-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_toparrival_topproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toparrival',
            name='body',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='toparrival',
            name='brandUrl',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='toparrival',
            name='cooking',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='toparrival',
            name='ingredient',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='toparrival',
            name='nutrition',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
