# Generated by Django 4.0.5 on 2022-08-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_topproducts_body_alter_topproducts_brandurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='body',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
