# Generated by Django 4.0.5 on 2022-08-12 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_meal_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakFast_Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('body', models.CharField(blank=True, max_length=10000)),
                ('brand', models.CharField(blank=True, max_length=10000)),
                ('brandUrl', models.CharField(blank=True, max_length=200)),
                ('calories', models.FloatField()),
                ('category', models.CharField(blank=True, max_length=200)),
                ('cooking', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('ingredient', models.CharField(blank=True, max_length=200)),
                ('nutrition', models.CharField(blank=True, max_length=200)),
                ('price', models.FloatField()),
                ('sale', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('weight', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Chicken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('body', models.CharField(blank=True, max_length=10000)),
                ('brand', models.CharField(blank=True, max_length=10000)),
                ('calories', models.FloatField()),
                ('image', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('sale', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('weight', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('body', models.CharField(blank=True, max_length=10000)),
                ('brand', models.CharField(blank=True, max_length=10000)),
                ('calories', models.FloatField()),
                ('image', models.CharField(max_length=200)),
                ('piece', models.CharField(blank=True, max_length=200)),
                ('price', models.FloatField()),
                ('sale', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('weight', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Keto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('brand', models.CharField(blank=True, max_length=10000)),
                ('brandUrl', models.CharField(blank=True, max_length=200)),
                ('calories', models.FloatField()),
                ('image', models.CharField(max_length=200)),
                ('nutrition', models.CharField(blank=True, max_length=200)),
                ('price', models.FloatField()),
                ('sale', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lunch_Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('body', models.CharField(blank=True, max_length=10000)),
                ('brand', models.CharField(blank=True, max_length=10000)),
                ('brandUrl', models.CharField(blank=True, max_length=200)),
                ('calories', models.FloatField()),
                ('category', models.CharField(blank=True, max_length=200)),
                ('cooking', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('ingredient', models.CharField(blank=True, max_length=200)),
                ('nutrition', models.CharField(blank=True, max_length=200)),
                ('price', models.FloatField()),
                ('sale', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('weight', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flavor', models.CharField(blank=True, max_length=10000)),
                ('company', models.CharField(blank=True, max_length=10000)),
                ('formation', models.CharField(blank=True, max_length=10000)),
                ('origin', models.CharField(blank=True, max_length=10000)),
                ('serving', models.CharField(blank=True, max_length=10000)),
                ('weight', models.CharField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('brand', models.CharField(blank=True, max_length=10000)),
                ('brandUrl', models.CharField(blank=True, max_length=200)),
                ('calories', models.FloatField()),
                ('image', models.CharField(max_length=200)),
                ('piece', models.CharField(blank=True, max_length=200)),
                ('price', models.FloatField()),
                ('sale', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('weight', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('body', models.CharField(blank=True, max_length=10000)),
                ('brand', models.CharField(blank=True, max_length=10000)),
                ('calories', models.FloatField()),
                ('image', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('sale', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('weight', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='meal',
            name='calroties',
        ),
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='piece',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='meal',
            name='weight',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='toparrival',
            name='weight',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Supplements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('body', models.CharField(blank=True, max_length=10000)),
                ('brand', models.CharField(blank=True, max_length=10000)),
                ('calories', models.FloatField()),
                ('image', models.CharField(max_length=200)),
                ('nutrition', models.CharField(blank=True, max_length=200)),
                ('price', models.FloatField()),
                ('sale', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('ProductData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductData', to='meals.productdata')),
            ],
        ),
    ]
