# Generated by Django 4.0.5 on 2022-08-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_breakfast_meals_chicken_fruit_keto_lunch_meal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='piece',
        ),
        migrations.AlterField(
            model_name='meal',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='brand',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meal',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
