# Generated by Django 4.0.5 on 2022-08-12 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_rename_category_id_meal_category_remove_meal_piece_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='meals.category_meal'),
        ),
    ]
