# Generated by Django 4.0.5 on 2022-08-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_alter_meal_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category_Meal',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='category',
            new_name='category_id',
        ),
        migrations.AddField(
            model_name='meal',
            name='piece',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='meal',
            name='amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='brand',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='sale',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
