# Generated by Django 4.0.5 on 2022-08-12 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_delete_category_meal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='piece',
            new_name='brandUrl',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='category_id',
        ),
        migrations.AddField(
            model_name='meal',
            name='cooking',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredient',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='meal',
            name='nutrition',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='meal',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='brand',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meal',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='meals.category_meals'),
            preserve_default=False,
        ),
    ]
