# Generated by Django 4.0.5 on 2022-08-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_category_meals_rename_piece_meal_brandurl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_LowCarb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LowCarb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('body', models.CharField(blank=True, max_length=10000)),
                ('brand', models.CharField(blank=True, max_length=10000)),
                ('brandUrl', models.CharField(blank=True, max_length=200)),
                ('calories', models.FloatField()),
                ('image', models.CharField(max_length=200)),
                ('nutrition', models.CharField(blank=True, max_length=200)),
                ('price', models.FloatField()),
                ('sale', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_lowcarb', to='meals.category_lowcarb')),
            ],
        ),
    ]
