# Generated by Django 4.0.5 on 2022-08-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0014_category_type_alter_lowcarb_category_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
