# Generated by Django 4.0.5 on 2022-08-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0015_rename_product_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=10000)),
                ('password', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
