# Generated by Django 4.0.5 on 2022-08-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0016_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_inst',
            field=models.BooleanField(default=False),
        ),
    ]
