# Generated by Django 4.0.5 on 2022-08-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0018_alter_register_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='is_inst',
        ),
    ]
