# Generated by Django 4.1 on 2022-08-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0019_remove_register_is_inst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bakeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=10000)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('calories', models.FloatField()),
                ('category', models.CharField(blank=True, max_length=200)),
                ('contain', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('ingredient', models.CharField(blank=True, max_length=200)),
                ('nutrition', models.CharField(blank=True, max_length=200)),
                ('price', models.FloatField()),
                ('sale', models.BooleanField(default=False)),
                ('storing', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=10000)),
                ('weight', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
