# Generated by Django 4.1 on 2022-08-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0021_alter_bakeries_category_alter_bakeries_contain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('body', models.CharField(blank=True, max_length=10000)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('brandUrl', models.CharField(blank=True, max_length=200)),
                ('calories', models.FloatField()),
                ('category', models.CharField(blank=True, max_length=2000)),
                ('image', models.CharField(max_length=2000)),
                ('ingredient', models.CharField(blank=True, max_length=2000)),
                ('nutrition', models.CharField(blank=True, max_length=200)),
                ('price', models.FloatField()),
                ('sale', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=10000)),
            ],
        ),
    ]
