# Generated by Django 3.2.14 on 2022-08-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0026_meat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10000)),
                ('body', models.CharField(blank=True, max_length=10000)),
                ('category', models.CharField(blank=True, max_length=2000)),
                ('image', models.CharField(max_length=2000)),
            ],
        ),
    ]
