# Generated by Django 3.2.14 on 2022-08-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0027_addedmeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addedmeal',
            name='category',
        ),
    ]
