# Generated by Django 3.2.14 on 2022-08-17 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0028_remove_addedmeal_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addedmeal',
            old_name='image',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='addedmeal',
            old_name='body',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='addedmeal',
            old_name='title',
            new_name='username',
        ),
    ]
