# Generated by Django 3.2.14 on 2022-08-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0030_auto_20220818_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedmeal',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
