# Generated by Django 3.2.14 on 2022-08-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0031_addedmeal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addedmeal',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
