# Generated by Django 3.2.14 on 2022-08-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0032_alter_addedmeal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedmeal',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
