# Generated by Django 3.2.14 on 2022-08-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0033_addedmeal_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddedMeal',
        ),
    ]
