# Generated by Django 3.2.14 on 2022-08-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0035_addedmeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addedmeal',
            name='completed',
        ),
    ]
