# Generated by Django 3.2.14 on 2022-08-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0036_remove_addedmeal_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedmeal',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='keto',
            name='completed',
            field=models.BooleanField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
