# Generated by Django 3.2.14 on 2022-08-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0037_auto_20220820_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keto',
            name='completed',
        ),
    ]
