# Generated by Django 3.2.14 on 2022-08-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0038_remove_keto_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addedmeal',
            name='image',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
