# Generated by Django 3.2.14 on 2022-08-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0042_vegan_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
